# Change these first
owner: devpetrate # Replace with your GitHub username
repo: zefyrswap-status # Your repository name
user-agent: zefyrswap

# Add your sites here
sites:
  - name: ZefyrSwap
    url: https://zefyrswap.com
    
  - name: ZefyrSwap API
    url: https://api.zefyrswap.com
    
  - name: ZefyrSwap App
    url: https://app.zefyrswap.com
    
  - name: Router Contract Health
    check: "tcp-ping"
    url: mainnet.base.org
    port: 443

# Status website configuration
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  cname: status.zefyrswap.com
  
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name here
  # baseUrl: /zefyrswap-status
  
  logoUrl: https://www.zefyrswap.com/logos/Zefyr.svg
  name: ZefyrSwap Status
  introTitle: "**ZefyrSwap** DEX Aggregator Status"
  introMessage: Real-time status and uptime monitoring for ZefyrSwap services
  
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/devpetrate/zefyrswap-status
    - title: ZefyrSwap
      href: https://zefyrswap.com

# Commit messages
commitMessages:
  readmeContent: ":pencil: Update summary in README [skip ci]"
  summaryJson: ":card_file_box: Update status summary [skip ci]"
  statusChange: "$EMOJI $SITE_NAME is $STATUS ($RESPONSE_CODE in $RESPONSE_TIME ms) [skip ci]"
  graphsUpdate: ":bento: Update graphs [skip ci]"

# Monitoring configuration
workflowSchedule:
  uptime: "*/5 * * * *"  # Check every 5 minutes
  responseTime: "0 */6 * * *"  # Record response time every 6 hours
  graphs: "0 2 * * *"  # Generate graphs daily at 2am
  staticSite: "0 3 * * *"  # Update status page daily at 3am

# Notification configuration (optional)
notifications:
  # - type: slack
  #   webhook-url: $SLACK_WEBHOOK_URL
  # Add Discord webhook if you prefer
  - type: discord
    webhook-url: $DISCORD_WEBHOOK_URL

# Response time configuration
assignees:
  - devpetrate

# PAT with repo scope
user-agent: zefyrswap
